baseURL = "http://localhost:1313" #"https://www.barefootbushwalk.blog/"
canonifyURLs = false

title = "Barefoot Bushwalk"
author = "The Barefoot Bushwalker"
copyright = "Copyright © 2023 The Barefoot Bushwalker."
paginate = 9
enableRobotsTXT = true
languageCode = "en-gb"
enableInlineShortcodes = true
# prevent build failures when using Hugo's Instagram shortcode due to deprecated Instagram API.
# See https://github.com/gohugoio/hugo/issues/7228#issuecomment-714490456
ignoreErrors = ["error-remote-getjson"]
enableEmoji = true
timeout = "60s"

# Multilingual
defaultContentLanguage = "en"
disableLanguages = ["nl"]

enableMissingTranslationPlaceholders = true

mainSections = ["blog"]

[taxonomies]
  tag = 'tags'

[privacy]
  [privacy.vimeo]
    disabled = false
    simple = true

  [privacy.twitter]
    disabled = false
    enableDNT = true
    simple = true

  [privacy.instagram]
    disabled = false
    simple = true

  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

[services]
  [services.instagram]
    disableInlineCSS = true
  [services.twitter]
    disableInlineCSS = true


[outputFormats]
  [outputFormats.XML]
    isPlainText = false
    mediaType = "application/xml"
    isHtml = false
    noUgly = true
    permalinkable = false
    name = "xml"

[module]
  [module.hugoVersion]
    extended = true
    min = "0.81.0"
    max = ""
 [[module.mounts]]
    source = "node_modules/@markdumay/hugo-theme-hinode/archetypes"
    target = "archetypes"
  [[module.mounts]]
    source = "node_modules/@markdumay/hugo-theme-hinode/assets"
    target = "assets"
  [[module.mounts]]
    source = "node_modules/@markdumay/hugo-theme-hinode/i18n"
    target = "i18n"
  [[module.mounts]]
    source = "node_modules/@markdumay/hugo-theme-hinode/layouts"
    target = "layouts"
  [[module.mounts]]
    source = "node_modules/@markdumay/hugo-theme-hinode/static"
    target = "static"
  [[module.mounts]]
    source = "node_modules/flexsearch"
    target = "assets/js/vendor/flexsearch"
  [[module.mounts]]
    source = "assets"
    target = "assets"
  [[module.mounts]]
    source = "i18n"
    target = "i18n"
  [[module.mounts]]
    source = "layouts"
    target = "layouts"
  [[module.mounts]]
    source = "static"
    target = "static"